### PR TITLE
Fix regex sort

### LINKED ISSUE #484: Bad regex sort when multiple paths match
Regex comparisons where both paths/basenames match incorrectly order the files, rather than allowing subsequent criteria to break the tie.

example where regex ordering breaks
1/a
1/a2
1/b
2/a
2/a2
2/b
pattern:
`x<1>r<a>l`

### PR DESCRIPTION
**Pull request by nloewen**
Fixes #484

### CODE REVIEW

File: lib/preprocess.c [hunk 1]
```diff
@@ -356,36 +356,43 @@ char *rm_pp_compile_patterns(RmSession *session, const char *sortcrit, GError **
...
         /* Match for the first time */
-        result = g_regex_match(regex, path_b, 0, NULL);
-        RM_PATTERN_SET_CACHED(mask_b, idx, result);
+        result_b = g_regex_match(regex, path_b, 0, NULL);
+        RM_PATTERN_SET_CACHED(mask_b, idx, result_b);
     }
 
-    if(result) {
-        return +1;
+    /* Both match */
```
Comment (SeeSpotRun) [inline lib/preprocess.c:380]: can use macro SIGN_DIFF here to simplify:
`    return SIGN_DIFF(result_b, result_a);`
Defined here: https://github.com/sahib/rmlint/blob/094fbd59cbfb2d2df73dacb0647aacc425982848/lib/utilities.h#L71

**Comment by SeeSpotRun** [comment]
Thanks, beat me to it.
