### PR TITLE
Fix sh escape emptydirs

### LINKED ISSUE #241: Characters not properly escaped or quoted in path
> remove_cmd '/home/user/mnt/usb/Backup/Desktop [20110731]/Documents/Java Documentation & Books/JDK 6 Docs/jre/api/security/smartcardio/spec/package-list' '/home/user/mnt/usb/Backup/Desktop [20110731-alt]/Documents/Java Documentation & Books/JDK 6 Docs/jre/api/security/smartcardio/spec/package-list' # duplicate

> [  3%] Deleting:  /home/user/mnt/usb/Backup/Desktop [20110731]/Documents/Java Documentation & Books/JDK 6 Docs/jre/api/security/smartcardio/spec/package-list
> ls: cannot access '[20110731]/Documents/Java': No such file or directory
> ls: cannot access 'Documentation': No such file or directory
> ls: cannot access '&': No such file or directory
> ls: cannot access 'Books/JDK': No such file or directory
> ls: cannot access '6': No such file or directory
> ls: cannot access 'Docs/jre/api/security/smartcardio/spec': No such file or directory

### PR DESCRIPTION
**Pull request by SeeSpotRun**
Should fix #241

### CODE REVIEW

File: lib/formats/sh.sh [hunk 1]
```diff
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 PROGRESS_CURR=0
-PROGRESS_TOTAL=                            
+PROGRESS_TOTAL=
```
Comment (sahib) [inline lib/formats/sh.sh]: We need these spaces here. The actual PROGRESS_TOTAL is written in the "blank space" by the hacky seek code. Please keep them.

Comment (SeeSpotRun) [inline lib/formats/sh.sh]: oooh, sneaky!

**Comment by sahib** [comment]
Ah no, it creates a long string in the output. TBH I think I favor something weird and hacky on the developer side, instead of leaking that through to the user script...
